name: Aggiornamento Lista IPTV

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  update-playlist:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout del repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Esecuzione dello script di ordinamento
        run: python ordina.py

      - name: Salvataggio e caricamento della nuova lista
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action Bot"
          git add lista_tivusat.m3u
          git commit -m "Aggiornamento lista e EPG" || exit 0
          git pull --rebase
          git push
          
